Update

diff --git a/shell/zshrc b/shell/zshrc
--- a/shell/zshrc
+++ b/shell/zshrc
@@ -1,17 +1,24 @@
 # Path to your oh-my-zsh installation.
 export ZSH=~/.oh-my-zsh
 
-export PATH=$PATH:/usr/local/bin/
+# ssh
+export SSH_KEY_PATH="~/.ssh/id_rsa"
+export PATH=$PATH:/usr/local/bin
 export PATH=$PATH:/usr/local/sbin
 export PATH=$PATH:/usr/local/MacGPG2/bin
 export PATH=$PATH:$PYTHONPATH
-export PATH="$HOME/.yarn/bin:$PATH"
+export PATH=$PATH:"$HOME/Library/Python/3.6/bin"
 
 export MANPATH="/usr/local/share/man:$MANPATH"
+
 export HOMEBREW_CASK_OPTS="--appdir=/Applications"
 
 export EDITOR="nvim"
-export MYNVIMRC="~/.config/nvim/init.vim"
+
+export MYNVIMRC=$HOME/.config/nvim/init.vim
+
+
+export PATH="$HOME/.yarn/bin:$PATH"
 
 # Set name of the theme to load.
 # Look in ~/.oh-my-zsh/themes/
@@ -30,13 +37,12 @@ DEFAULT_USER=`whoami`
 # DISABLE_AUTO_UPDATE="true"
 
 # Uncomment the following line to change how often to auto-update (in days).
-# export UPDATE_ZSH_DAYS=13
+export UPDATE_ZSH_DAYS=4
 
 # Uncomment the following line to disable colors in ls.
 # DISABLE_LS_COLORS="true"
 
 # Uncomment the following line to disable auto-setting terminal title.
-
 DISABLE_AUTO_TITLE="true"
 
 # Uncomment the following line to enable command auto-correction.
@@ -118,38 +124,57 @@ man() {
             man "$@"
 }
 
-# ssh
-export SSH_KEY_PATH="~/.ssh/id_rsa"
-
 # Set personal aliases, overriding those provided by oh-my-zsh libs,
 # plugins, and themes. Aliases can be placed here, though oh-my-zsh
 # users are encouraged to define aliases within the ZSH_CUSTOM folder.
 # For a full list of active aliases, run `alias`.
-alias r='ruby'
 alias n='nvim'
+alias reattach='tmux attach-session -t'
+alias rez='tmux attach || { (while ! tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh; do sleep 0.2; done)& tmux ; }'
+
 # alias cd='cs'
+alias irb='irb --simple-prompt'
+# alias python='python3'
+# alias pip='pip3'
+
+
+# Don't autocorrect ripgrep to `gr`, which is Git Remote alias from git plugin
+# -uu searches hidden files and directories
+# Useful when looking for .directories
+
 alias gc='git commit -v -S'
 alias gd='git difftool'
 alias kk='clear'
-alias irb='irb --simple-prompt'
 alias bgrep='/usr/bin/grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
 alias ggpush='git push -u origin $(git_current_branch)'
+
+
+export FZF_DEFAULT_COMMAND='rg --files --hidden --smart-case --follow --glob "!.git/*"'
 
 test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
 
 
-# ===============================================
+# # ===============================================
 
-# ORDER
+# # ORDER
 SPACESHIP_PROMPT_ORDER=(
   time
   user
   host
   dir
   git
+  hg
   node
   ruby
   elixir
+  xcode
+  swift
+  golang
+  rust
+  haskell
+  docker
+  venv
+  pyenv
   exec_time
   line_sep
   vi_mode
@@ -158,50 +183,50 @@ SPACESHIP_PROMPT_ORDER=(
   char
 )
 
-# PROMPT
-SPACESHIP_PROMPT_SYMBOL="➜"
-SPACESHIP_PROMPT_ADD_NEWLINE=true
-SPACESHIP_PROMPT_SEPARATE_LINE=true
-SPACESHIP_PROMPT_PREFIXES_SHOW=true
-SPACESHIP_PROMPT_SUFFIXES_SHOW=true
-SPACESHIP_PROMPT_DEFAULT_PREFIX=""
-SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "
+# # PROMPT
+# SPACESHIP_PROMPT_SYMBOL="➜"
+# SPACESHIP_PROMPT_ADD_NEWLINE=true
+# SPACESHIP_PROMPT_SEPARATE_LINE=true
+# SPACESHIP_PROMPT_PREFIXES_SHOW=true
+# SPACESHIP_PROMPT_SUFFIXES_SHOW=true
+# SPACESHIP_PROMPT_DEFAULT_PREFIX=""
+# SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "
 
-# TIME
-SPACESHIP_TIME_SHOW=false
-SPACESHIP_TIME_PREFIX="at "
-SPACESHIP_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_TIME_FORMAT=false
-SPACESHIP_TIME_12HR=false
-SPACESHIP_TIME_COLOR="yellow"
+# # TIME
+# SPACESHIP_TIME_SHOW=false
+# SPACESHIP_TIME_PREFIX="at "
+# SPACESHIP_TIME_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_TIME_FORMAT=false
+# SPACESHIP_TIME_12HR=false
+# SPACESHIP_TIME_COLOR="yellow"
 
-# EXECUTION TIME
-SPACESHIP_EXEC_TIME_SHOW="${SPACESHIP_EXEC_TIME_SHOW:=true}"
-SPACESHIP_EXEC_TIME_PREFIX="${SPACESHIP_EXEC_TIME_PREFIX:="took "}"
-SPACESHIP_EXEC_TIME_SUFFIX="${SPACESHIP_EXEC_TIME_SUFFIX:="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
-SPACESHIP_EXEC_TIME_COLOR="${SPACESHIP_EXEC_TIME_COLOR:="yellow"}"
-SPACESHIP_EXEC_TIME_THRESHOLD="${SPACESHIP_EXEC_TIME_THRESHOLD:=5000}"
-SPACESHIP_EXEC_TIME_MS="${SPACESHIP_EXEC_TIME_MS:=false}"
+# # EXECUTION TIME
+# SPACESHIP_EXEC_TIME_SHOW="${SPACESHIP_EXEC_TIME_SHOW:=true}"
+# SPACESHIP_EXEC_TIME_PREFIX="${SPACESHIP_EXEC_TIME_PREFIX:="took "}"
+# SPACESHIP_EXEC_TIME_SUFFIX="${SPACESHIP_EXEC_TIME_SUFFIX:="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
+# SPACESHIP_EXEC_TIME_COLOR="${SPACESHIP_EXEC_TIME_COLOR:="yellow"}"
+# SPACESHIP_EXEC_TIME_THRESHOLD="${SPACESHIP_EXEC_TIME_THRESHOLD:=5000}"
+# SPACESHIP_EXEC_TIME_MS="${SPACESHIP_EXEC_TIME_MS:=false}"
 
-# USER
-SPACESHIP_USER_SHOW=true
-SPACESHIP_USER_PREFIX="with "
-SPACESHIP_USER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_USER_COLOR="yellow"
-SPACESHIP_USER_COLOR_ROOT="red"
+# # USER
+# SPACESHIP_USER_SHOW=true
+# SPACESHIP_USER_PREFIX="with "
+# SPACESHIP_USER_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_USER_COLOR="yellow"
+# SPACESHIP_USER_COLOR_ROOT="red"
 
-# HOST
-SPACESHIP_HOST_SHOW=true
-SPACESHIP_HOST_PREFIX="at "
-SPACESHIP_HOST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_HOST_COLOR="green"
+# # HOST
+# SPACESHIP_HOST_SHOW=true
+# SPACESHIP_HOST_PREFIX="at "
+# SPACESHIP_HOST_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_HOST_COLOR="green"
 
-# DIR
-SPACESHIP_DIR_SHOW=true
-SPACESHIP_DIR_PREFIX="in "
-SPACESHIP_DIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_DIR_TRUNC=3
-SPACESHIP_DIR_COLOR="cyan"
+# # DIR
+# SPACESHIP_DIR_SHOW=true
+# SPACESHIP_DIR_PREFIX="in "
+# SPACESHIP_DIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_DIR_TRUNC=3
+# SPACESHIP_DIR_COLOR="cyan"
 
 # GIT
 SPACESHIP_GIT_SHOW=true
@@ -230,47 +255,48 @@ SPACESHIP_GIT_STATUS_BEHIND="⇣"
 SPACESHIP_GIT_STATUS_DIVERGED="⇕"
 
 
-# NODE
-SPACESHIP_NODE_SHOW=true
-SPACESHIP_NODE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
-SPACESHIP_NODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_NODE_SYMBOL=""
-SPACESHIP_NODE_DEFAULT_VERSION=""
-SPACESHIP_NODE_COLOR="green"
+# # NODE
+# SPACESHIP_NODE_SHOW=true
+# SPACESHIP_NODE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
+# SPACESHIP_NODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_NODE_SYMBOL=""
+# SPACESHIP_NODE_DEFAULT_VERSION=""
+# SPACESHIP_NODE_COLOR="green"
 
-# RUBY
-SPACESHIP_RUBY_SHOW=true
-SPACESHIP_RUBY_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
-SPACESHIP_RUBY_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_RUBY_SYMBOL=""
-SPACESHIP_RUBY_COLOR="red"
+# # RUBY
+# SPACESHIP_RUBY_SHOW=true
+# SPACESHIP_RUBY_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
+# SPACESHIP_RUBY_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_RUBY_SYMBOL=""
+# SPACESHIP_RUBY_COLOR="red"
 
-# ELIXIR
-SPACESHIP_ELIXIR_SHOW=true
-SPACESHIP_ELIXIR_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
-SPACESHIP_ELIXIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_ELIXIR_SYMBOL=""
-SPACESHIP_ELIXIR_DEFAULT_VERSION=""
-SPACESHIP_ELIXIR_COLOR="magenta"
+# # ELIXIR
+# SPACESHIP_ELIXIR_SHOW=true
+# SPACESHIP_ELIXIR_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"
+# SPACESHIP_ELIXIR_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_ELIXIR_SYMBOL=""
+# SPACESHIP_ELIXIR_DEFAULT_VERSION=""
+# SPACESHIP_ELIXIR_COLOR="magenta"
 
-# VI_MODE
-SPACESHIP_VI_MODE_SHOW=true
-SPACESHIP_VI_MODE_PREFIX=""
-SPACESHIP_VI_MODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
-SPACESHIP_VI_MODE_INSERT="[I]"
-SPACESHIP_VI_MODE_NORMAL="[N]"
-SPACESHIP_VI_MODE_COLOR="white"
+# # VI_MODE
+# SPACESHIP_VI_MODE_SHOW=true
+# SPACESHIP_VI_MODE_PREFIX=""
+# SPACESHIP_VI_MODE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"
+# SPACESHIP_VI_MODE_INSERT="[I]"
+# SPACESHIP_VI_MODE_NORMAL="[N]"
+# SPACESHIP_VI_MODE_COLOR="white"
 
-# JOBS
-SPACESHIP_JOBS_SHOW="true"
-SPACESHIP_JOBS_PREFIX="("
-SPACESHIP_JOBS_SUFFIX=") "
-SPACESHIP_JOBS_SYMBOL=$(jobscount)
-SPACESHIP_JOBS_COLOR="blue"
+# # JOBS
+# SPACESHIP_JOBS_SHOW="true"
+# SPACESHIP_JOBS_PREFIX="("
+# SPACESHIP_JOBS_SUFFIX=") "
+# SPACESHIP_JOBS_SYMBOL=$(jobscount)
+# SPACESHIP_JOBS_COLOR="blue"
 
-# EXIT CODE
-SPACESHIP_EXIT_CODE_SHOW=true
-SPACESHIP_EXIT_CODE_PREFIX="("
-SPACESHIP_EXIT_CODE_SUFFIX=") "
-SPACESHIP_EXIT_CODE_SYMBOl="✘ "
-SPACESHIP_EXIT_CODE_COLOR="red"
+# # EXIT CODE
+# SPACESHIP_EXIT_CODE_SHOW=true
+# SPACESHIP_EXIT_CODE_PREFIX="("
+# SPACESHIP_EXIT_CODE_SUFFIX=") "
+# SPACESHIP_EXIT_CODE_SYMBOl="✘ "
+# SPACESHIP_EXIT_CODE_COLOR="red"
+
